### ISSUE TITLE
scroller-page 参数什么意思，不明白为什么这么写

### ISSUE THREAD

**Issue by liyeyu** [wzs28150/coolui-scroller#13]
<scroller-page wx:for="{{ list }}" id="wrp_{{pageIndex}}" wx:for-index="pageIndex" wx:for-item="listSingleItem" wx:key="index" pageList="{{ listSingleItem }}">
      
      <item wx:for="{{ listSingleItem }}" wx:for-index="index" wx:for-item="listItem" wx:key="index">
        
        <view class="item">
          <image class='item-image' lazy-load="{{true}}" src="{{listItem.img}}"></image>
          <view class="item-title">{{(pageIndex * 3) + listItem.id}}.{{listItem.title}}</view>
        </view>
      </item>
      
    </scroller-page>

**Comment by wzs28150** [comment]
截图挂掉了 没看到啊
