### ISSUE TITLE
企业微信小程序模式下有问题，运行报错

### ISSUE THREAD

**Issue by Bighappiness** [wzs28150/coolui-scroller#14]
![image](https://user-images.githubusercontent.com/7802101/145844139-6e9cc51e-4284-4b1f-ab65-4985f40db241.png)

**Comment by wzs28150** [comment]
你用的是哪个版本？

**Comment by Bighappiness** [comment]
v3.0

**Comment by wzs28150** [comment]
有没有片段，我这实在不知道怎么复现你这个报错

**Comment by Bighappiness** [comment]
你好，就是在git上拉下来的代码，开发模式切换到企业微信小程序模式就报错了，正常的小程序模式ok的

**Comment by wzs28150** [comment]
1.报错原因找到了：是我尝试item添加点击波纹效果测试的时候设置的传参错误
![image](https://user-images.githubusercontent.com/21290257/147845097-523ce224-e71f-4402-940c-3f2e68aaefe7.png)
修改成下图这样即可
![image](https://user-images.githubusercontent.com/21290257/147845098-5dcf9592-7bac-4eab-8d0c-e8bc9c0ec281.png)
我会马上更新解决
2.scroll-view组件在企业微信小程序模式下，下拉异常 ，所以暂不支持企业微信小程序， 我已经像官方提交等待回复中

**Comment by wzs28150** [comment]
组件请使用v3.0.6版

**Comment by Bighappiness** [comment]
好的，感谢
