### ISSUE TITLE
isBackBtn="{{true}}" 能不能改成不是刷新数据而是返回到顶部？

### ISSUE THREAD

**Issue by FellowTraveler9** [wzs28150/coolui-scroller#16]

**Comment by wzs28150** [comment]
能改成滚动到顶部 ，下个版本加上。主要scroll-view想要滚动到某一位置需要做标记。这样意义大不大？刷新也是从头开始列表- -

**Comment by wzs28150** [comment]
请更新V3.0.5，返回到顶部已修改

**Comment by FellowTraveler9** [comment]
好的

**Comment by FellowTraveler9** [comment]
刷新会增加服务器的I/O




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月27日(星期一) 上午10:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wzs28150/coolui-scroller] isBackBtn=&quot;{{true}}&quot; 能不能改成不是刷新数据而是返回到顶部？ (Issue #16)





 
能改成滚动到顶部 ，下个版本加上。主要scroll-view想要滚动到某一位置需要做标记。这样意义大不大？刷新也是从头开始列表- -
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
