### ISSUE TITLE
与 Van 的 Tab 一起使用，只显示第一页的内容

### ISSUE THREAD

**Issue by yuandoudou928** [wzs28150/coolui-scroller#17]
您好！我在使用下拉刷新和上拉加载，搭配 Vant 的 "Tab 标签页"，只有第一个页面能现在布局，后面的页面都不显示，请问您知道怎么修改吗？
![image](https://user-images.githubusercontent.com/16776103/149288327-a324a075-6c36-4d77-be8d-d1c6c8376c0a.png)
![image](https://user-images.githubusercontent.com/16776103/149290384-529f509b-06b2-4234-a6ce-5fe24b198640.png)
![image](https://user-images.githubusercontent.com/16776103/149290602-471cf9ee-2f21-49a0-ac58-c33b598a6d26.png)

**Comment by wzs28150** [comment]
你要把滚动拿到外面来使用，然后根据active来判断加载的是哪个tab下的 ，不要加载过多的列表。
![image](https://user-images.githubusercontent.com/21290257/149610937-dc406e1d-21a2-4886-b358-2f6d2edd65ca.png)
tab里是可以留空的 然后根据切换事件刷新列表就好

**Comment by wzs28150** [comment]
你可以参考组件demo里的组合使用

**Comment by yming** [comment]
这种情况把滚动scroller放在van-tab外面后，就无法使用refresh 和 loadmore了吧，refresh还是要在tab标签的下面和列表挨着的。这种场景貌似没有办法scroller+van-tab+refresh 同时使用，只能全部使用coolui提供的scroller+nav+refresh这种实现
