### ISSUE TITLE
下拉刷新和加载更多的事件触发有延迟

### ISSUE THREAD

**Issue by yming** [wzs28150/coolui-scroller#18]
下拉刷新和加载更多的触发有延迟，再加上接口请求时间，导致整体数据显示延迟较高，可否立即触发事件，谢谢

**Comment by wzs28150** [comment]
为了防止频繁触发，在刷新和加载的时候，使用了debounce。 你项目中的这个文件 miniprogram_npm/coolui-scroller/scroller/index.js ，102行onLoadmore方法中的数字500， 
![image](https://user-images.githubusercontent.com/21290257/153122000-2dc8dbcd-04f1-4e9c-b6dc-7d3e13cd994f.png)

调小一下，记得清理文件缓存和编译缓存，看看上拉加载延迟是否有好转。同理，该文件中用到debounce方法的地方你都试下，如有好转我会把这个数值作为参数在下个版本改进下。

**Comment by yming** [comment]
> 为了防止频繁触发，在刷新和加载的时候，使用了debounce。 你项目中的这个文件 miniprogram_npm/coolui-scroller/scroller/index.js ，102行onLoadmore方法中的数字500， 
> 
> ![image](https://user-images.githubusercontent.com/21290257/153122000-2dc8dbcd-04f1-4e9c-b6dc-7d3e13cd994f.png)
> 
> 
> 
> 调小一下，记得清理文件缓存和编译缓存，看看上拉加载延迟是否有好转。同理，该文件中用到debounce方法的地方你都试下，如有好转我会把这个数值作为参数在下个版本改进下。

谢谢，我试下

**Comment by wzs28150** [comment]
> > 为了防止频繁触发，在刷新和加载的时候，使用了debounce。 你项目中的这个文件 miniprogram_npm/coolui-scroller/scroller/index.js ，102行onLoadmore方法中的数字500，
> > ![image](https://user-images.githubusercontent.com/21290257/153122000-2dc8dbcd-04f1-4e9c-b6dc-7d3e13cd994f.png)
> > 调小一下，记得清理文件缓存和编译缓存，看看上拉加载延迟是否有好转。同理，该文件中用到debounce方法的地方你都试下，如有好转我会把这个数值作为参数在下个版本改进下。
> 
> 谢谢，我试下

请问调整数值 延迟是否有好转？ 是我组件的问题还是其他问题呢？
