### ISSUE TITLE
全局设置名为`flex`的class，引起警告：设置 enable-flex 属性以使 flexbox 布局生效

### ISSUE THREAD

**Issue by uniblackfire** [wzs28150/coolui-scroller#19]
我在全局设置了一个class
```css
.flex {
display:flex;
}
```
微信开发者工具的console发出警告：设置 enable-flex 属性以使 flexbox 布局生效
查询发现[https://developers.weixin.qq.com/community/develop/doc/00068cac8e05d8ac2ae86d8fc5ec00](https://developers.weixin.qq.com/community/develop/doc/00068cac8e05d8ac2ae86d8fc5ec00) 这里提示要增加`enable-flex`属性到scroll-view

查看了`coolui-scroller/scroller/index.wxml`的第5行，使用了flex这样一个class，可能这里受到了我全局class的影响

**Comment by wzs28150** [comment]
好的 我看下

**Comment by wzs28150** [comment]
![image](https://user-images.githubusercontent.com/21290257/157372712-5313a3d5-bcb5-49b2-8271-5cc3b5b81749.png)
![image](https://user-images.githubusercontent.com/21290257/157372312-31585adb-e1bc-4b06-919a-9d26b1040dd4.png)
不知道您是如何使用的 ,因为item并没有直接在scroll-view里的第一层, 所以直接开启也可能作用不到。如果可能请包裹一层带flex样式的结构。不过我还是加上了这个设置在V3.0.9  https://wzs28150.github.io/coolui-scroller/v3/components/scroller.html#%E9%85%8D%E7%BD%AE
