### ISSUE TITLE
空状态时 class slot-empty有背景色

### ISSUE THREAD

**Issue by uniblackfire** [wzs28150/coolui-scroller#20]
目前我的项目采用了van-empty作为空状态的提示，但是默认的empty slot具有class slot-empty，因此导致背景色不一致。
.slot-empty {
  // 修复下拉组件空状态时有背景色的问题
  background-color: unset !important;
}
我在全局设置了这样一个class 用来取消您组件里的空状态背景色，但是还是希望可以提供方法来取消，谢谢

**Comment by wzs28150** [comment]
收到 感谢 我处理一下
