### ISSUE TITLE
loadMoreSetting.status为noMore的时候，无法下拉刷新

### ISSUE THREAD

**Issue by uniblackfire** [wzs28150/coolui-scroller#21]
loadMoreSetting.status为noMore的时候，无法下拉刷新

**Comment by wzs28150** [comment]
下拉刷新并没有判断loadMoreSetting的状态哦。loadMoreSetting的status完全是为了控制加载条状态的，是在你调用的时候设置的。有代码片段么？我可以帮你看看

**Comment by uniblackfire** [comment]
https://github.com/wzs28150/coolui-scroller/blob/6d24a86de9923b349ad61de8dc8ecc0137647ced/miniprogram_dev/pages/combined/index.js#L108

我把demo分支的combined页面上，请求参数isempty设置为1，此时无法下拉刷新

**Comment by uniblackfire** [comment]
scroller组件上设置isEmpty属性，似乎就会使得无法下拉刷新？
