### ISSUE TITLE
refresh组件type="default"时，isAutoTriggered设置false无效，无法手动控制何时收回

### ISSUE THREAD

**Issue by yming** [wzs28150/coolui-scroller#22]

**Comment by wzs28150** [comment]
只有开启自定义的时候才能控制何时收回 ，系统自带的效果没办法控制。 isAutoTriggered 我应该在文档上提示下

**Comment by yming** [comment]
系统的效果，是否可以通过使refresh支持传递scroll-view的这两个属性来支持呢？   refresher-enabled  refresher-triggered

**Comment by wzs28150** [comment]
你要是真的喜欢这个效果可以用自定义模式  然后view写三个圆点闪烁一下。你说的那两个就是开启自定义了。你可以看下refresh组件去写一下圆点就能实现控制了。
