### ISSUE TITLE
scroller组件bug，在弹出框里面嵌套这个scroller这个组件，获取的高度为0

### ISSUE THREAD

**Issue by javeyG** [wzs28150/coolui-scroller#25]
`我现在修改是通过定时器去修改，如以下代码`
 ready() {
    setTimeout(() => {
      this.setWapHeight()
    }, 300)
    this.refreshNodes = this.getRelationNodes('../refresh/index')
    this.refreshNode = this.refreshNodes[0] ? this.refreshNodes[0] : null
  },
看是否引用以上建议

**Comment by wzs28150** [comment]
抱歉最近有点忙，scroller 默认组件是高度100%, 组件是随着外侧结构的高度变得。你的弹出框里有设置高度么?还是说弹出框由于起初隐藏而没有获取到高度？

**Comment by javeyG** [comment]
弹出框一开始是隐藏的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月15日(星期三) 晚上6:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wzs28150/coolui-scroller] scroller组件bug，在弹出框里面嵌套这个scroller这个组件，获取的高度为0 (Issue #25)





 
抱歉最近有点忙，scroller 默认组件是高度100%, 组件是随着外侧结构的高度变得。你的弹出框里有设置高度么?还是说弹出框由于起初隐藏而没有获取到高度？
