### ISSUE TITLE
使用了hidden之后导致的高度问题

### ISSUE THREAD

**Issue by linjulong** [wzs28150/coolui-scroller#26]
版本是3.x，有下面一个问题：
业务场景：有两个tab，tab里面都是放了两个上拉加载更多，第一个直接显示，第二个给了hidden来切换显示（如图下）
![image](https://user-images.githubusercontent.com/51310488/168952674-1e24a93b-cd5b-4e65-82e1-1cb87631856b.png)
但是会发现一个bug，就是你切过去之后，第二个列表内容不会显示（如果用wx:if则会显示）。经过深入探究发现原来是hidden导致的问题，导致了scroll-view获取的高度为0了（如下图），这个怎么处理好呢？因为我总不能切换tab之后就重新渲染组件吧？（会重新刷新数据了），所以是不是源码中的获取高度的地方得改改呢？
![b48bca3472f9132f152ea2048203049](https://user-images.githubusercontent.com/51310488/168952820-a31a5633-2583-4fff-ba80-84aa258bfdea.png)
![image](https://user-images.githubusercontent.com/51310488/168952909-25354a86-77c8-4e57-8db8-2044e34c22e1.png)

**Comment by wzs28150** [comment]
最好就是使用一个滚动加载组件，tab只负责切换 ，然后拿到切换之后的id去请求数据更新列表
