### ISSUE TITLE
IOS手机下拉刷新无法触发

### ISSUE THREAD

**Issue by liknzero** [wzs28150/coolui-scroller#3]
IOS手机下拉的时候会有自带的弹性下拉，所以下拉刷新与界面默认下拉冲突导致不能触发下拉事件

**Comment by wzs28150** [comment]
本身这个组件是基于 scroll-view 组件来封装的。scroll-view就是局部滚动的，在使用这个组件的时候你需要将页面设置高度100vw 禁用页面的滚动才行,该组件只适用于那些页面主要是列表的情况下。如果要整个页面滚动 请使用小程序的onPullDownRefresh来实现
