### ISSUE TITLE
refresh组件，背景色设置无效

### ISSUE THREAD

**Issue by cvpv** [wzs28150/coolui-scroller#31]
![image](https://user-images.githubusercontent.com/84720311/197924661-93fd96e4-f02f-41be-8c0a-9746650451bc.png)

**Comment by cvpv** [comment]
在您提供的官方demo上复现

**Comment by cvpv** [comment]
通过以下方法实现了，
![Snipaste_2022-10-26_17-20-38](https://user-images.githubusercontent.com/84720311/197988317-16dbdc8a-72d9-41c9-9a1e-4048c53cb63d.png)
但是还是希望您能更新下文档，既然config中color无用，就删掉这个参数吧

**Comment by wzs28150** [comment]
![image](https://user-images.githubusercontent.com/21290257/198019946-724ea238-5985-4ce8-b84c-771748b0830d.png)

**Comment by wzs28150** [comment]
> 通过以下方法实现了， ![Snipaste_2022-10-26_17-20-38](https://user-images.githubusercontent.com/84720311/197988317-16dbdc8a-72d9-41c9-9a1e-4048c53cb63d.png) 但是还是希望您能更新下文档，既然config中color无用，就删掉这个参数吧

最近scroll-view 官方修复了bug 我也修复了下 还没有提交代码
