### ISSUE TITLE
下拉组件有问题

### ISSUE THREAD

**Issue by cvpv** [wzs28150/coolui-scroller#33]
下拉组件拉到一点点松手会触发加载中，然后无论等多久，下次下拉一定是加载中图标和"下拉刷新字样"！

**Comment by cvpv** [comment]
![Honeycam 2022-10-27 11-36-50](https://user-images.githubusercontent.com/84720311/198185477-3e0e8d3a-4236-46be-874b-c458f5cf0c9a.gif)

**Comment by cvpv** [comment]
而且也没有下拉刷新字样，只有松手刷新，您看，这个问题能看看吗

**Comment by cvpv** [comment]
还是非常感谢您能提供如此简单、文档全面、开箱即用的作品。

**Comment by wzs28150** [comment]
ok 我排查一下

**Comment by wzs28150** [comment]
> 还是非常感谢您能提供如此简单、文档全面、开箱即用的作品。

也感谢你的反馈~

**Comment by wzs28150** [comment]
> 下拉组件拉到一点点松手会触发加载中，然后无论等多久，下次下拉一定是加载中图标和"下拉刷新字样"！

请升级v3.1.2. 由于下拉不到位，回弹之后没有触发回弹的方法，从而一些状态没有更新造成的
