### ISSUE TITLE
【严重】scroller高度计算，在IOS设备下异常！

### ISSUE THREAD

**Issue by cvpv** [wzs28150/coolui-scroller#34]

**Comment by cvpv** [comment]
微信版本8.0.29

**Comment by cvpv** [comment]
实测排查原因可能是boundingClientRect获取高度异常
![image](https://user-images.githubusercontent.com/84720311/198209593-c94029cd-b1bc-4a85-a996-494f121c89ff.png)
使用延迟渲染能解决（dom设置wx:if）

**Comment by cvpv** [comment]
该问题，在iPhone设备下复现，安卓正常，开发者工具正常，iPhone真机调试正常

**Comment by cvpv** [comment]
https://developers.weixin.qq.com/community/develop/doc/000a8822934250620fa6406d756400?highLine=boundingClientRect%2520ios

**Comment by HailPHP** [comment]
> 实测排查原因可能是boundingClientRect获取高度异常 ![image](https://user-images.githubusercontent.com/84720311/198209593-c94029cd-b1bc-4a85-a996-494f121c89ff.png) 使用延迟渲染能解决（dom设置wx:if）

大佬，这个地方没太理解如何解决在ios上的问题，安卓是正常的
我的场景是好几个一级tab swpier里面 嵌套的scroller组件，然后部分一级下还有一个二级tab，所以高度会不一样

现在问题就是ios上明显内容高度超出显示滚动条了，无数据的empty都可以滑动，想问下您说的延迟渲染 dom设置wx:if,是设置在哪个dom上呢？
