### ISSUE TITLE
请问一下，如何配合tab做滑动悬停效果

### ISSUE THREAD

**Issue by zhuoshirong** [wzs28150/coolui-scroller#35]

**Comment by wzs28150** [comment]
有效果图或者例子么 你说的滑动悬停效果我脑子里没什么概念呢

**Comment by zhuoshirong** [comment]
demo： https://developers.weixin.qq.com/s/p7cvcPmG7cAN 类似这种效果，这个是代码片段，scrollview里面做吸顶，我试了好几种兼容都不怎么好，感谢大佬

**Comment by wzs28150** [comment]
加个联系方式吧  qq:1003418012 在这探讨太费劲

**Comment by wzs28150** [comment]
你用的position: sticky;实现的吸顶，在开发者工具和安卓上可能没问题，ios上可能有问题。你看下官方给的组件https://github.com/wechat-miniprogram/miniprogram-component-plus/tree/master/src/sticky

**Comment by zhuoshirong** [comment]
官方的组件我看也是用的 position: fixed，差不多一样的
.weui-sticky__fixed {
  position: fixed;
  left: 0;
  top: 0;
}

**Comment by wzs28150** [comment]
> 官方的组件我看也是用的 position: fixed，差不多一样的 .weui-sticky__fixed { position: fixed; left: 0; top: 0; }

...那不一样啊  fixed 和 sticky 兼容性不一样啊 想要完美实现就得搭配js计算滚动位置 去定位
![image](https://user-images.githubusercontent.com/21290257/211494592-4b6cbbd9-36c4-4e13-8d3c-c8559773a43d.png)
