### ISSUE TITLE
loadmore,字体颜色设置无效

### ISSUE THREAD

**Issue by ulyanovsk** [wzs28150/coolui-scroller#36]
<block wx:if="{{status === 'more'}}" style="color: {{more.color}}">{{more.text}}</block>
<block wx:elif="{{status === 'noMore'}}" style="color: {{noMore.color}}">{{noMore.text}}</block>

more.color和noMore.color颜色设置无效，要么改下标签block为text吧

**Comment by wzs28150** [comment]
已解决 请安装最新版v3.1.4

**Comment by yisirman** [comment]
v3.3.2版本还是不生效？

**Comment by wzs28150** [comment]
更新一下3.3.3
