### ISSUE TITLE
下拉刷新在真机上效果非常卡顿

### ISSUE THREAD

**Issue by Martin0207** [wzs28150/coolui-scroller#40]
请问，我这边使用中，在开发工具中运行预览，滑动很流畅。
但是真机预览或发布后，在手机上下拉刷新会非常卡顿。
扫描文档中的二维码，测试下拉效果，也非常卡顿。
有什么办法可以消除这个问题吗？
感谢

**Comment by Martin0207** [comment]
是用的是最新版本："coolui-scroller": "^3.3.2"

**Comment by wzs28150** [comment]
你用的是ios还是安卓？
