### ISSUE TITLE
"coolui-scroller": "^3.3.3",存在滑动抖动的bug

### ISSUE THREAD

**Issue by HaoClaimLin** [wzs28150/coolui-scroller#46]
在iOS机型先缓慢下拉刷新，刷新结束后再缓慢下拉刷新就会出现列表整体抖动的问题，演示小程序的“组合使用”里就可以复现，同样的步骤，Android机型上的现象是卡顿

**Comment by wzs28150** [comment]
收到近期优化一下~

**Comment by darcy521** [comment]
我也是遇到跟楼上一样的问题，各个组件单独拉出来使用是没有问题的，但一旦嵌入自己其他的代码就会一直报这个错误
![image](https://github.com/user-attachments/assets/9b72c4a6-7584-4a18-96d7-7a97f87f8402)
![image](https://github.com/user-attachments/assets/2fba7461-7be5-4a29-ab8c-d9d72e415713)
从这个情况来看backToTopNodes并没有得到任何的数据，且封装的getRelationNodes得不到任何东西
且内部.data.threshold并没有相关定义的东西

**Comment by wzs28150** [comment]
https://wzs28150.github.io/coolui-scroller/v3/version.html#v3-3-5
