### ISSUE TITLE
在引用组件界面是否支持bindscroll监听？

### ISSUE THREAD

**Issue by Pandaqing** [wzs28150/coolui-scroller#48]
在引用组件界面是否支持bindscroll监听？
比如像在监听滚动停止后, 处理一些事情.
或者isBackBtn是否支持启用滚动停止后设置多少秒进行隐藏isBackBtn, 因为如果isBackBtn一直显示的话, 在界面中会遮挡一些操作，以至于每个界面都得去调整它的bottom

**Comment by wzs28150** [comment]
修改中 一会升级一版

**Comment by wzs28150** [comment]
https://wzs28150.github.io/coolui-scroller/v3/version.html#v3-3-4
