### ISSUE TITLE
逻辑错误导致未显示   " 没有更多了 " 文本

### ISSUE THREAD

**Issue by liganghui** [wzs28150/coolui-scroller#8]
针对版本为 v2.0.2

![微信截图_20210226100041](https://user-images.githubusercontent.com/15844198/109244342-88d35980-7819-11eb-9097-e5cde2037e29.png)

**Comment by liganghui** [comment]
追加一个问题 . 再使用中出现 上拉触底loading一直显示  无法触发加载问题 .   修改高度单位为vh可解决
![image](https://user-images.githubusercontent.com/15844198/109246990-23359c00-781e-11eb-88ff-941087dae8f6.png)

**Comment by wananzys** [comment]
这个问题确实明显
